---
extends:
  - plugin:react/recommended
  - eslint:recommended
  - airbnb-base
env:
  browser: true,
  amd: true,
  jquery: true,
  es6: true,
  node: true,
  jest: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
    experimentalDecorators: true

settings:
  react:
    version: 'detect'

globals:
  __DEV__: true
  __SERVER__: true

plugins:
  - react
  - jest
rules:
  max-len:
    [
      1,
      120,
      2,
      {
        ignoreComments: true,
        ignoreUrls: true,
        ignoreRegExpLiterals: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
      },
    ]
  quote-props: [2, 'as-needed']
  radix: 0
  space-infix-ops: 1
  default-case: 0
  no-else-return: 0
  no-param-reassign: 0
  semi: [2, 'always']
  func-names: 0
  object-shorthand: [1, 'consistent-as-needed']
  quotes: [2, 'single', { avoidEscape: true, allowTemplateLiterals: true }]
  indent: [2, 2, { SwitchCase: 1 }]
  no-tabs: 0
  no-template-curly-in-string: 0
  no-undef: 2
  eqeqeq: [2, 'smart']
  no-useless-concat: 0
  no-plusplus: 0
  no-empty: 2
  one-var-declaration-per-line: 0
  one-var: 0
  comma-dangle: 0
  prefer-arrow-callback: 1
  eol-last: 1
  no-underscore-dangle: 0
  consistent-return: 0
  no-shadow: 2
  prefer-const: 1
  no-loop-func: 1
  no-continue: 0
  prefer-rest-params: 1
  no-nested-ternary: 1
  no-prototype-builtins: 0
  no-restricted-properties: 0
  no-unused-expressions: [1, { allowTernary: true, allowShortCircuit: true }]
  no-multi-assign: 0
  no-case-declarations: 1
  guard-for-in: 0
  no-restricted-syntax: 0
  strict: 0
  no-mixed-operators: [1, { allowSamePrecedence: true }]
  global-require: 0
  import/no-dynamic-require: 0
  newline-per-chained-call: 0
  spaced-comment: 1
  class-methods-use-this: 0
  no-cond-assign: 2
  no-unused-vars:
    [2, { 'vars': 'local', 'args': 'none', 'ignoreRestSiblings': true }]
  react/prop-types: [2, { 'ignore': ['children'] }]
  curly: 2
  jsx-quotes: [1, 'prefer-single']
  no-constant-condition: 2
  valid-typeof: 2
  no-catch-shadow: 2
  import/no-extraneous-dependencies: 0
  import/first: 0
  import/prefer-default-export: 0
  import/no-webpack-loader-syntax: 0
  import/no-unresolved: 0
  import/extensions: 0
  import/no-duplicates: 0
  import/no-named-as-default: 0
  arrow-parens: 0
  camelcase: 0
